In [170]:
!pip install numpy

In [171]:
import numpy as np

In [172]:
print(np.__version__)

2.0.2


In [173]:
# 1. Creating Arrays

In [174]:
list1=[1,2,3]
print(list1)
print(list1*2)

[1, 2, 3]
[1, 2, 3, 1, 2, 3]


In [175]:
arr_list=np.array(list1)
print(arr_list)
print(arr_list*2)

[1 2 3]
[2 4 6]


In [176]:
print(type(arr_list))

<class 'numpy.ndarray'>


In [177]:
print(arr_list.ndim)

1


In [178]:
list1=[1,2,3]
list2=[4,5,6]
arr_list2=np.array([list1,list2])
print(arr_list2)

[[1 2 3]
 [4 5 6]]


In [179]:
print(arr_list2.ndim)

2


In [180]:
list1=[1,2,3]
list2=[4,5,6]
list3=[7,8,9]
arr_list3=np.array([[list1,list2,list3]])
print(arr_list3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [181]:
print(arr_list3.ndim)

3


In [182]:
# 2. Numpy Array Attributes

In [183]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [184]:
print("Shape: ",arr1.shape)
print("Size: ",arr1.size)
print("dType: ",arr1.dtype)
print("n_dim: ",arr1.ndim)

Shape:  (2, 3)
Size:  6
dType:  int64
n_dim:  2


In [185]:
# 3. Array Intialization Methods

In [186]:
# Zero Array
zero_arr=np.zeros((2,3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [187]:
# One Array
one_arr=np.ones((2,3))
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [188]:
# Full Array
full_arr=np.full((2,3),2)
print(full_arr)

[[2 2 2]
 [2 2 2]]


In [189]:
# Identity Matrix
id_arr=np.eye(4)
print(id_arr)
print(id_arr.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
2


In [190]:
# Empty Array
emp_arr=np.empty(2)
print(emp_arr)

[5.43230922e-312 7.29112202e-304]


In [191]:
# Evenly Spaced Array
esp_arr=np.arange(1,10,4)
print(esp_arr)

[1 5 9]


In [192]:
# Specific number of equally (spaced) values between a range
print(np.linspace(1,10,4))

[ 1.  4.  7. 10.]


In [193]:
# Random Value Array - float
r_arr=np.random.rand(3,2)
print(r_arr)

[[0.02833251 0.58485177]
 [0.60948425 0.25732844]
 [0.5780947  0.92886944]]


In [263]:
# Random Value Array - float
# np.random.seed(1)
ri_arr=np.random.randint(1,100,(2,2))
print(ri_arr)

[[38 13]
 [73 10]]


In [264]:
# Array Indexing and Slicing
a=np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [196]:
print(a[0])
print(a[2])
print(a[-1])

1
5
9


In [197]:
# Slicing
# array[start:stop:step]
# stop index is excluded
print(a[0:3])
print(a[2:5])

[1 3 5]
[5 7 9]


In [198]:
print(a[0:5:2])
print(a[::])

[1 5 9]
[1 3 5 7 9]


In [199]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [200]:
print(arr2[0])
print(arr2[1])
print(arr2[0][0])

[1 2 3]
[4 5 6]
1


In [201]:
print(arr2[1])
print(arr2[0:])

[4 5 6]
[[1 2 3]
 [4 5 6]]


In [202]:
print(arr2[:,1])

[2 5]


In [203]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [204]:
print(arr3[0])
print(arr3[:])

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [205]:
print(arr3[0][0])
print(arr3[:,2])

1
[3 6 9]


In [206]:
print(arr3[::2,2])
print(arr3[:,1:2])

[3 9]
[[2]
 [5]
 [8]]


In [234]:
# Boolean Filtering
sales = np.array([100,250,150,400,300])
print(sales > 200)
print(sales[sales > 200])
print(sales[(sales > 200) & (sales < 400)])
np.where(sales > 200)
np.where(sales > 200, "High", "Low")

[False  True False  True  True]
[250 400 300]
[250 300]


array(['Low', 'High', 'Low', 'High', 'High'], dtype='<U4')

In [240]:
# Axis
sales = np.array([
    [100,200,300],
    [400,500,600]
])
print(np.sum(sales))
print(np.sum(sales, axis=0))
print(np.sum(sales, axis=1))

2100
[500 700 900]
[ 600 1500]


In [243]:
# ravel()
a = np.array([
    [1,2,3],
    [4,5,6]
])
print(a.ravel())

[1 2 3 4 5 6]


In [244]:
# Joining arrays
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]


In [246]:
# split
a = np.array([1,2,3,4,5,6])
np.split(a, 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [247]:
# np.unique()
industry = np.array([
    "Tech",
    "Finance",
    "Tech",
    "Healthcare",
    "Finance"
])
print(np.unique(industry))

['Finance' 'Healthcare' 'Tech']


In [249]:
# Sorting
a = np.array([40,10,30,20])
print(np.sort(a))

[10 20 30 40]


In [252]:
# argmax() and argmin()
sales = np.array([100,500,200,800,300])
print(np.max(sales))
print(np.argmax(sales))
print(np.argmin(sales))

800
3
0


In [208]:
# 5. Array Reshaping and Flattening

In [209]:
arr1=np.array([1,2,3,4,5,6,7,8])
print(arr1)

[1 2 3 4 5 6 7 8]


In [210]:
reshaped=arr1.reshape((8,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [211]:
reshaped1=arr1.reshape((2,4))
print(reshaped1)

[[1 2 3 4]
 [5 6 7 8]]


In [212]:
print(reshaped1.flatten())

[1 2 3 4 5 6 7 8]


In [213]:
# 6. Array Stacking and Splitting

In [214]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [215]:
c=np.array([[1,2,3],[4,5,6]])
print(np.hsplit(c,3))
print(np.vsplit(c,2))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [216]:
# 7. Mathematical Operations on Array
a=np.array([10,20,30,-10])
print(a)

[ 10  20  30 -10]


In [217]:
print(a+10)
print(a-5)
print(a*2)
print(a/10)
print(a**2)

[20 30 40  0]
[  5  15  25 -15]
[ 20  40  60 -20]
[ 1.  2.  3. -1.]
[100 400 900 100]


In [265]:
b=np.array([4,9,16])
print(np.square(b))
print(np.sqrt(b))
print(np.sin(b))
print(np.cos(b))
print(np.tan(b))
print(np.abs(b))
print(np.round(b))
print(np.floor(b))
print(np.ceil(b))

[ 16  81 256]
[2. 3. 4.]
[-0.7568025   0.41211849 -0.28790332]
[-0.65364362 -0.91113026 -0.95765948]
[ 1.15782128 -0.45231566  0.30063224]
[ 4  9 16]
[ 4  9 16]
[ 4.  9. 16.]
[ 4.  9. 16.]


In [219]:
# 8. Mathematical Operations on Multiple Array

In [220]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [221]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [222]:
print(np.dot(a,b))

32


In [223]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [224]:
# 9. Statistical Functions
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [235]:
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))

15
3.0
3.0
1.4142135623730951
2.0
1
5


In [226]:
# 10. Array Comparison
a=np.array([1,5,6])
b=np.array([4,5,6])
print(a)
print(b)

[1 5 6]
[4 5 6]


In [227]:
print(a==b)
print(np.array_equal(a,b))

[False  True  True]
False


In [228]:
# 11. Broadcasting
a=np.array([1,2,3,4,5])
b=np.array([4])
print(a+b)

[5 6 7 8 9]


In [274]:
# 12. Handling with nan & inf
d=np.array([1,2,3,np.nan,5,np.nan])
x=np.array([1,2,3,np.nan,5,np.inf])
print(d)
print(np.mean(d))
print(np.nanmean(d))
print(np.nansum(d))
print(np.nanmin(d))
print(np.nanmax(d))
print(np.nanmedian(d))
print(np.nanstd(d))

[ 1.  2.  3. nan  5. nan]
nan
2.75
11.0
1.0
5.0
2.5
1.479019945774904


In [275]:
print(np.isnan(d))
print(np.isinf(x))

[False False False  True False  True]
[False False False False False  True]


In [276]:
print(np.nan_to_num(d))

[1. 2. 3. 0. 5. 0.]


In [277]:
# 13. Save and load array
arr1=np.array([1,2,3])
print(arr1)
np.save('myarr.npy',arr1)

[1 2 3]


In [278]:
l_arr=np.load('myarr.npy')
print(l_arr)

[1 2 3]
